# Generated by Django 5.2 on 2025-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='element',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='Способ применения'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
