# Generated by Django 5.2 on 2025-06-19 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0006_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата консультации')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Витамин/Элемент')),
                ('min_normal', models.FloatField(verbose_name='Минимальная норма')),
                ('max_normal', models.FloatField(verbose_name='Максимальная норма')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('element', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitamin_data', to='bio_core_website.element')),
            ],
        ),
        migrations.CreateModel(
            name='VitaminLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Уровень')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitamin_levels', to='bio_core_website.consultation')),
                ('vitamin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_core_website.vitamin')),
            ],
            options={
                'unique_together': {('consultation', 'vitamin')},
            },
        ),
    ]
