# Generated by Django 5.2 on 2025-06-19 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0007_consultation_vitamin_vitaminlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='vitamin',
            name='danger_high_level',
            field=models.BooleanField(default=True, verbose_name='Предупреждать о высоком уровне'),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='high_level_message',
            field=models.TextField(default='Проконсультируйтесь со специалистом', verbose_name='Сообщение при высоком уровне'),
        ),
        migrations.CreateModel(
            name='UserBMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='bio_core_website.element')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_core_website.manufacturer')),
            ],
            options={
                'ordering': ['-is_main', 'manufacturer__name'],
                'unique_together': {('element', 'manufacturer')},
            },
        ),
    ]
