# Generated by Django 5.2 on 2025-06-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0008_remove_element_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='bio_core_website.manufacturer', verbose_name='Производитель'),
        ),
        migrations.DeleteModel(
            name='ElementManufacturer',
        ),
    ]
