# Generated by Django 5.2 on 2025-06-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0009_element_manufacturer_delete_elementmanufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='manufacturer',
        ),
        migrations.CreateModel(
            name='ElementManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='bio_core_website.element')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_links', to='bio_core_website.manufacturer')),
            ],
            options={
                'unique_together': {('element', 'manufacturer')},
            },
        ),
    ]
