# Generated by Django 5.2 on 2025-06-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0010_remove_element_manufacturer_elementmanufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmanufacturer',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_manufacturers', to='bio_core_website.element'),
        ),
        migrations.AlterField(
            model_name='elementmanufacturer',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_manufacturers', to='bio_core_website.manufacturer'),
        ),
    ]
