# Generated by Django 5.2 on 2025-06-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0012_element_manufacturers_delete_elementmanufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bio_core_website.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='element',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, help_text='Выберите одного или нескольких производителей', to='bio_core_website.manufacturer', verbose_name='Производители'),
        ),
    ]
