# Generated by Django 5.2 on 2025-06-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0013_alter_element_category_alter_element_manufacturers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='bio_core_website.category', verbose_name='Категория'),
        ),
    ]
