# Generated by Django 5.2 on 2025-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio_core_website', '0014_alter_element_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ролика')),
                ('video_file', models.FileField(upload_to='promo_videos/', verbose_name='Видеофайл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рекламный ролик',
                'verbose_name_plural': 'Рекламные ролики',
            },
        ),
    ]
