# Generated by Django 5.2 on 2025-06-20 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bio_core_website', '0015_promovideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['name'], 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='promovideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рекламный ролик', 'verbose_name_plural': 'Рекламные ролики'},
        ),
        migrations.AlterModelOptions(
            name='userbmi',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'BMI пользователя', 'verbose_name_plural': 'BMI пользователей'},
        ),
        migrations.AlterModelOptions(
            name='vitamin',
            options={'verbose_name': 'Витамин', 'verbose_name_plural': 'Витамины'},
        ),
        migrations.AlterModelOptions(
            name='vitaminlevel',
            options={'verbose_name': 'Уровень витамина', 'verbose_name_plural': 'Уровни витаминов'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='bio_core_website.category'),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='element',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, to='bio_core_website.manufacturer'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='element',
            name='usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promovideo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='promovideo',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promovideo',
            name='video_file',
            field=models.FileField(upload_to='promo_videos/'),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='bmi',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userbmi',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='danger_high_level',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='high_level_message',
            field=models.TextField(default='Проконсультируйтесь со специалистом'),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='max_normal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='min_normal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vitaminlevel',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['user', 'date'], name='consultation_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='user_username_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['name', 'category'], name='element_name_category_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['name'], name='manufacturer_name_idx'),
        ),
        migrations.AddIndex(
            model_name='userbmi',
            index=models.Index(fields=['user', 'date'], name='bmi_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='userbmi',
            index=models.Index(fields=['bmi'], name='bmi_value_idx'),
        ),
        migrations.AddIndex(
            model_name='vitamin',
            index=models.Index(fields=['name'], name='vitamin_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vitamin',
            index=models.Index(fields=['min_normal', 'max_normal'], name='vitamin_normal_range_idx'),
        ),
        migrations.AddIndex(
            model_name='vitaminlevel',
            index=models.Index(fields=['consultation'], name='vitaminlevel_consultation_idx'),
        ),
        migrations.AddIndex(
            model_name='vitaminlevel',
            index=models.Index(fields=['vitamin'], name='vitaminlevel_vitamin_idx'),
        ),
    ]
